name: Publish To npm
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope       : 'base64-emoji-parser'
          always-auth : true
      - name: can publish
        run : npx can-npm-publish --verbose
      - name: install
        run : npm install
      - name: build
        run : npm run build --if-present
      - name: test
        run: npm run test
      - name: publish
        run : npm publish --access=public
        env :
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
